import {test} from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import {readFileSync} from 'node:fs';
const html=readFileSync(new URL('../templates/utils/local_model_status.html',import.meta.url),'utf8');
const profiles=[{id:'qwen3.5-9b-q8',name:'Qwen3.5-9B Q8',expectedModel:'Qwen3.5-9B',available:true,unavailableReason:null}];
const state=(extra={})=>({success:true,state:'unloaded',profiles,profileId:null,loadedProfileId:null,model:null,endpoint:'http://127.0.0.1:18081',identityVerified:false,processMemoryMiB:null,processMemorySource:null,systemMemory:{totalMiB:16384,availableMiB:8000,usedMiB:8384,source:'psutil_virtual_memory'},...extra});
class Element{constructor(){this.events={};this.dataset={};this.value='';this.textContent='';this.checked=false;this.disabled=false;this.classes=new Set();this.classList={toggle:(key,on)=>on?this.classes.add(key):this.classes.delete(key),add:key=>this.classes.add(key),remove:key=>this.classes.delete(key)};}addEventListener(k,fn){this.events[k]=fn;}setAttribute(k,v){this[k]=v;}fire(k){return this.events[k]?.({preventDefault(){},target:this});}}
function setup(initial=state()){
 const nodes=new Map(),requests=[],timers=new Map();let timerId=0;
 const get=id=>{if(!nodes.has(id))nodes.set(id,new Element());return nodes.get(id);};
 const radios=profiles.map(p=>{const el=get('choice-'+p.id);el.value=p.id;el.dataset.profileId=p.id;return el;});
 const document={getElementById:get,querySelectorAll:()=>radios};
 const context=vm.createContext({document,window:{APP_CSRF_TOKEN:'test-csrf',addEventListener(){}},Date,AbortController,URL,console,setTimeout:fn=>{timers.set(++timerId,fn);return timerId;},clearTimeout:id=>timers.delete(id),fetch:(url,options={})=>new Promise((resolve,reject)=>requests.push({url,options,resolve,reject}))});
 const source=html.split('// BEGIN local model controls')[1]?.split('// END local model controls')[0];assert.ok(source,'new model controls required');vm.runInContext(source,context);
 const flush=async()=>{for(let i=0;i<20;i++)await Promise.resolve();};
 const reply=async(index,data,ok=true,status=200)=>{requests[index].resolve({ok,status,json:async()=>data});await flush();};
 const initialized=reply(0,initial);return{get,radios,requests,reply,flush,initialized,timers};
}
test('unloaded/uninstalled and missing memory are explicit; no automatic load',async()=>{const unavailable=profiles.map(p=>({...p,available:false,unavailableReason:'NOT_INSTALLED'}));const x=setup(state({profiles:unavailable}));await x.initialized;assert.match(x.get('modelRuntimeStatus').textContent,/未加载/);assert.match(x.get('availability-qwen3.5-9b-q8').textContent,/未安装/);assert.match(x.get('processMemory').textContent,/未采样/);assert.equal(x.requests.length,1);assert.equal(x.requests[0].options.method,'GET');});
test('only matching ready identity can green the approved 9B card',async()=>{const x=setup(state({state:'ready',profileId:'qwen3.5-9b-q8',loadedProfileId:'qwen3.5-9b-q8',model:'Qwen3.5-9B',identityVerified:true}));await x.initialized;assert.ok(x.get('card-qwen3.5-9b-q8').classes.has('model-ready'));assert.equal(x.requests.length,1);assert.equal(x.get('loadModel').disabled,true);});
test('ready with wrong alias/profile or unverified identity never greens',async()=>{for(const extra of [{model:'wrong',identityVerified:true},{model:'Qwen3.5-9B',identityVerified:false},{model:'Qwen3.5-9B',identityVerified:true,loadedProfileId:'legacy-2b'}]){const x=setup(state({state:'ready',profileId:'qwen3.5-9b-q8',loadedProfileId:'qwen3.5-9b-q8',...extra}));await x.initialized;assert.ok(!x.get('card-qwen3.5-9b-q8').classes.has('model-ready'));assert.match(x.get('modelRuntimeStatus').textContent,/故障/);}});
test('load posts approved 9B profile ID and CSRF once; busy failure retains selection and enables retry',async()=>{const x=setup();await x.initialized;const first=x.get('loadModel').fire('click');x.get('loadModel').fire('click');assert.equal(x.requests.length,2);const req=x.requests[1];assert.equal(req.url,'/utils/api/local-model/load');assert.equal(req.options.headers['X-CSRF-Token'],'test-csrf');assert.deepEqual(JSON.parse(req.options.body),{profileId:'qwen3.5-9b-q8'});assert.equal(x.get('unloadModel').disabled,true);await x.reply(1,{success:false,errorCode:'MODEL_BUSY'},false,409);assert.equal(x.get('loadModel').disabled,true);await x.reply(2,state());await first;assert.match(x.get('modelActionMessage').textContent,/使用|切换/);assert.equal(x.radios[0].checked,true);assert.equal(x.get('loadModel').disabled,false);});
test('unload uses empty payload and renders server unloaded state',async()=>{const x=setup(state({state:'ready',profileId:'qwen3.5-9b-q8',loadedProfileId:'qwen3.5-9b-q8',model:'Qwen3.5-9B',identityVerified:true,processMemoryMiB:9500,processMemorySource:'ps_rss'}));await x.initialized;assert.match(x.get('processMemory').textContent,/9500/);const action=x.get('unloadModel').fire('click');assert.deepEqual(JSON.parse(x.requests[1].options.body),{});await x.reply(1,state());await x.reply(2,state());await action;assert.match(x.get('modelRuntimeStatus').textContent,/未加载/);assert.ok(!x.get('card-qwen3.5-9b-q8').classes.has('model-ready'));});
test('failed status still shows controlled profiles and never estimates memory',async()=>{const x=setup(state({success:false,state:'failed',errorCode:'IDENTITY_MISMATCH',processMemoryMiB:'100',processMemorySource:'ps_rss',systemMemory:{totalMiB:null,availableMiB:null,source:null}}));await x.initialized;assert.match(x.get('modelRuntimeStatus').textContent,/故障/);assert.match(x.get('modelRuntimeDetails').textContent,/身份/);assert.match(x.get('systemMemory').textContent,/未采样/);assert.match(x.get('processMemory').textContent,/未采样/);assert.equal(x.radios[0].disabled,false);});
test('9B display name may differ from verified model alias',async()=>{const x=setup(state({state:'ready',profiles:profiles.map(p=>({...p,available:true})),profileId:'qwen3.5-9b-q8',loadedProfileId:'qwen3.5-9b-q8',model:'Qwen3.5-9B',identityVerified:true}));await x.initialized;assert.ok(x.get('card-qwen3.5-9b-q8').classes.has('model-ready'));assert.equal(x.get('name-qwen3.5-9b-q8').textContent,'Qwen3.5-9B Q8');});
test('loading locks all mutations and status outage removes stale green',async()=>{const x=setup(state({state:'loading',profileId:'qwen3.5-9b-q8'}));await x.initialized;assert.match(x.get('modelRuntimeStatus').textContent,/加载中/);assert.equal(x.get('loadModel').disabled,true);assert.equal(x.get('unloadModel').disabled,true);const refresh=x.get('refreshModelStatus').fire('click');x.requests[1].reject(new Error('offline'));await x.flush();await refresh;assert.match(x.get('modelRuntimeStatus').textContent,/故障/);assert.ok(!x.get('card-qwen3.5-9b-q8').classes.has('model-ready'));});
test('CSRF rejection is understandable, selection preserved, no automatic retry POST',async()=>{const x=setup();await x.initialized;const action=x.get('loadModel').fire('click');await x.reply(1,{error:{code:'CSRF_REJECTED'}},false,403);await x.reply(2,state());await action;assert.match(x.get('modelActionMessage').textContent,/重新登录/);assert.equal(x.requests.filter(r=>r.options.method==='POST').length,1);assert.equal(x.radios[0].checked,true);});
test('late status GET cannot overwrite post-operation current state',async()=>{const x=setup();await x.initialized;const prior=x.get('refreshModelStatus').fire('click');const action=x.get('loadModel').fire('click');await x.reply(2,state({state:'ready',profileId:'qwen3.5-9b-q8',loadedProfileId:'qwen3.5-9b-q8',model:'Qwen3.5-9B',identityVerified:true}));await x.reply(3,state({state:'ready',profileId:'qwen3.5-9b-q8',loadedProfileId:'qwen3.5-9b-q8',model:'Qwen3.5-9B',identityVerified:true}));await action;await x.reply(1,state());await prior;assert.ok(x.get('card-qwen3.5-9b-q8').classes.has('model-ready'));});

test('unknown operation outcome stays locked until actual status read completes',async()=>{const x=setup();await x.initialized;const action=x.get('loadModel').fire('click');x.requests[1].reject(new Error('network'));await x.flush();assert.equal(x.get('loadModel').disabled,true);assert.match(x.get('modelActionMessage').textContent,/未确认/);await x.reply(2,state());await action;assert.equal(x.get('loadModel').disabled,false);assert.equal(x.requests.filter(r=>r.options.method==='POST').length,1);});

// Stable controller profile id includes quantization; display names are not API identifiers.
test('installed 9B Q8 contract profile is selectable and posts exact stable id',async()=>{const readyProfiles=profiles.map(p=>({...p,available:true,unavailableReason:null}));const x=setup(state({profiles:readyProfiles}));await x.initialized;x.radios[0].checked=true;x.radios[0].fire('change');assert.equal(x.get('loadModel').disabled,false);assert.ok(!x.get('card-qwen3.5-9b-q8').classes.has('model-ready'));const action=x.get('loadModel').fire('click');assert.deepEqual(JSON.parse(x.requests[1].options.body),{profileId:'qwen3.5-9b-q8'});await x.reply(1,state({profiles:readyProfiles}));await x.reply(2,state({profiles:readyProfiles}));await action;});
